language: go

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew upgrade && brew install oniguruma ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then apt-get update && apt-get upgrade && apt-get install libonig-dev ; fi

install:
  - echo "Skipping install phase, because github.com/fstab/grok_exporter has all its dependencies in the vendor/ folder."

script:
  - go version
  - go test $(go list ./... | grep -v /vendor/)

go:
- tip
