version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\go\src\github.com\fstab\grok_exporter

environment:
 PATH: c:\go\bin;%PATH%
 GOPATH: c:\go
 NOTIFY_TIMEOUT: 5s

build_script:
 - go version
 - go test -v github.com/fstab/grok_exporter/config
 - go test -v github.com/fstab/grok_exporter/dummy_glog
 - go test -v github.com/fstab/grok_exporter/logger
 - go test -v github.com/fstab/grok_exporter/metrics
 - go test -v github.com/fstab/grok_exporter/server
 - go test -v github.com/fstab/grok_exporter/tailer

test: off

deploy: off
